### PR TITLE
Adding cookieconsent.com banner to site_header_extras() function and …

### PR DESCRIPTION
**Pull request by ADernild**
Adding cookieconsent.com banner to site_header_extras() function and modifying google analytics to let cookieconsent banner toggle it's cookie.

cookieconsent.com banner can be manipulated through the _site.yml with the tags:

```
cookie_consent:
    style: simple/headline/interstitial/standalone
    type: express/implied
    palette: light/dark
    lang: en/de/fr/es/ca_es/it/nl/pt/fi/hu/cs/hr/da/sl/pl/ro/sr/bg/cy
    privacy_policy: link to privacy policy
```

### CODE REVIEW

**Comment by jjallaire** [comment]
Thank you! Could you include a section in the documentation as part of the PR?

**Comment by ADernild** [comment]
> Thank you! Could you include a section in the documentation as part of the PR?

Yes I'm working on it! I was thinking of adding the section to website.Rmd just after the section on Google Analytics.

**Comment by jjallaire** [comment]
What happens if a site uses GA but doesn't configure Cookie Content? It looks to me from the code as if GA would fail to load, is that correct? If that's true I think we need either:

1) Make Cookie Consent optional; or 

2) Stop with an error if GA is configured but not cookie consent.

In the interests of not breaking existing sites I think we should do (1). Or perhaps I misunderstand the code and there is no issue. LMK.

**Comment by ADernild** [comment]
> What happens if a site uses GA but doesn't configure Cookie Content? It looks to me from the code as if GA would fail to load, is that correct? If that's true I think we need either:
> 
> 1. Make Cookie Consent optional; or
> 2. Stop with an error if GA is configured but not cookie consent.
> 
> In the interests of not breaking existing sites I think we should do (1). Or perhaps I misunderstand the code and there is no issue. LMK.

Yes you are absolutely correct, I didn't think of this when I wrote the code. Forgive me for my rookie mistakes, I'm still very new to coding. I too think we should go with (1) to ensure we don't break existing sites or force people to update. Could we make a check to see if Cookie Consent is configured and conditionally set GA and Disqus script type, to either "text/plain" or "text/javascript"?

**Comment by jjallaire** [comment]
Yes, your proposal makes sense!

**Comment by jjallaire** [comment]
This PR looks ready to merge! Thank you :-)

We are just about to do a CRAN release so will merge after the release (enough changes here that I don't want this landing at the 11th hour of a release).

**Comment by ADernild** [comment]
Sounds good! Thanks for the help, making this PR ready :)

**Pull request merged**
