### PR TITLE
Added new "collections:posts:custom" parameter to _site.yml config.

### PR DESCRIPTION
**Pull request by chrisrmiller**
* HTML contents are placed at the top right corner of the page, above "Subscribe" and "Categories".
* More flexible than "subscribe" in that it does not apply a ("&lt;h3&gt;Subscribe&lt;/h3&gt;") header.
* Useful for adding a search bar, author bio, etc. to the top right corner of the posts page.
* Content is not added to the article footers as there are already other mechanisms to do that.

Hi. This is my first pull request, so please excuse me if I'm not quite following the correct protocol. This feature is just something I've wanted since I started building my Distill blog. Please let me know if there's anything I can add/change/rename to help get this added upstream. Thanks!

### CODE REVIEW

**Comment by jjallaire** [comment]
This is great! Thanks :-)

The changes to distill-interactive-document.html appear to be just whitespace not related to the PR. Could we remove that file from the PR?

Could you add something to the docs about the custom feature?

**Comment by chrisrmiller** [comment]
Hi @jjallaire 

Glad to hear! Absolutely. I'll clean that bit up and include some documentation. I already have a working search bar on my site (through DuckDuckGo) so I might use that as the example code, unless you have something else in mind. Expect some more commits in the next day or so, and I'll leave another comment when it's ready. Thanks!

**Comment by jjallaire** [comment]
That seems like a great example. Thanks again!

**Comment by chrisrmiller** [comment]
Hi again. 

I pushed some more updates. I changed the functionality slightly since last time. Originally the custom HTML was automatically wrapped in a &lt;div class="sidebar-section custom"&gt; for ease-of-use. I found in my experimenting that this was rather confusing if you wished to apply your own CSS, or to define multiple sidebar sections within that one HTML file. Ultimately I decided it was better to hide less from the user in order to make the custom HTML structure easily understandable. Let me know what you think. We can certainly go back to the original method.

Thanks,

Chris

**Comment by chrisrmiller** [comment]
Forgot to knit. Oops :)

**Comment by jjallaire** [comment]
Terrific! This is a great feature. Thanks so much for the contribution.

**Pull request merged**
