### PR TITLE
Use "English" for LC_TIME on windows

### PR DESCRIPTION
**Pull request by jjallaire**
@cderv Does this look like the right fix for the first issue?

LMK if you are able to reproduce the `read_xml.character` error.

### CODE REVIEW

**Review by cderv — APPROVED** [review]
Yes this works. No more warning and date is in English locale now even on my French computer. 

This will be a breaking change for windows user with non-english locale as for now the date is formatted with this function using their current locale. This formatted date is used in the output post, right? Maybe worth mentioning in NEWS. 

Also FYI `is_windows()` and similar are in **xfun** that you already import. But that is an easy enough wrapper.

**Comment by jjallaire** [comment]
This date is just used in the RSS feed so the appearance of the post shouldn't be affected.

**Comment by jjallaire** [comment]
@cderv  Are you seeing it somewhere besides the RSS feed?

**Comment by cderv** [comment]
I check and I don't see it elsewhere. In fact, I saw it is stored in the metadata as `metadata$published_date_rfc` and thought it was used somewhere. I did not search thoroughly the code and in fact it seems it is not used. 

So no impact unless RSS feed.

**Pull request merged**
